Dev componente header
ImpulsoGov/DesignSystem pull request #10
Opened 2022-05-20 16:26 UTC by dlopes14

- Componente Header

2022-05-21 03:23 UTC, gabriellearruda commented
Por algum motivo não estou conseguindo mais rodar os componentes da sua branch.
Por hora o que posso comentar que já tinha visto da ultima vez que tinha conseguido rodar é o seguinte:
- O tamanho do texto do subtitulo nos tamanhos large e xlarge parciam conflituosos, o do xlarge parecia muito maior. Além disso o espaçamento a esquerda, não parecia proporcional nos diferentes tipos de telas; 
- Gostaria de saber se é possível o botão e do texto ao lado do botao ter hoover;
- Gostaria de saber se as cores estão já prontas para serem recebidas por paramero (acho que talvez não valha a pena fazer se não estiver feito, só quero saber como esta);
Pode me dar um retorno se esses pointos já habiam sido vistos enquanto eu tento rodar a branch? 
@dlopes14

2022-05-23 03:34 UTC, dlopes14 commented
- O problema do render do catalog foi devido a alteração do README do footer, vide o pull da branch do footer
- Novo Ajuste da responsividade 
- Hover do botão e da chamada implementados
- Na nossa ultima conversa havia entendido que  a prioridade era a construção de novos componentes e que esse ajuste seria feito em outra task

2022-05-23 04:18 UTC, gabriellearruda requested changes
1. O problema do render do catalog: Tudo resolvido 👍
2. Novo Ajuste da responsividade: Parece melhor, ainda acho que xlarge talvez precise ter o tamanho ajustado, mas isso depois revemos com a Ro 👍
3. Hover do botão e da chamada: Acho que não fui muito clara aqui sobre o tipo de alteração em hoover. Esse é outro aspecto que deveria ver com a Ro, mas como primeira versão poderia ser alteração de cor (do botão e do texto ao lado), para depois discutirmos. Assim poderia no hoover trocar o background pelo laranja? Estou requisitando essa alteração⚠️.
4. Parametro de cor: Tudo bem, acho que podemos seguir continuando com essa ordem de tarefas e depois revemos a questão da dor 👍

2022-05-24 01:32 UTC, gabriellearruda approved these changes

2022-05-24 03:02 UTC, merged